include: package:very_good_analysis/analysis_options.2.3.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/injectable.config.dart"
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    public_member_api_docs: false
